#!/usr/bin/env python3
"""Cold-chain sensor simulator for the LogiBridge Edge AI pipeline.

Assignment component: C1

The simulator publishes:

* Temperature readings at 1 Hz
* Vibration RMS readings at 0.5 Hz
* Discrete door OPEN/CLOSE events
* A combined sensor-state stream at 1 Hz

Supported anomaly modes:

* none
* temp_drift
* vibration
* combined

Example:

    python data_pipeline/simulator.py \
        --truck-id TRUCK-001 \
        --anomaly none \
        --duration 60
"""

from __future__ import annotations

import argparse
import json
import logging
import random
import signal
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any

import numpy as np
import paho.mqtt.client as mqtt


LOGGER = logging.getLogger("logibridge.simulator")

TEMPERATURE_SAMPLE_INTERVAL_SECONDS = 1.0
VIBRATION_SAMPLE_INTERVAL_SECONDS = 2.0

NORMAL_TEMPERATURE_MEAN_C = 4.0
NORMAL_TEMPERATURE_STD_C = 0.3

NORMAL_VIBRATION_MEAN_G = 0.45
NORMAL_VIBRATION_STD_G = 0.05

DEFAULT_DOOR_EVENT_PROBABILITY = 0.02
DEFAULT_QOS = 1


@dataclass
class SensorState:
    """Latest values generated by the sensor simulator."""

    temperature_c: float
    vibration_rms_g: float
    door_state: str


class LogiBridgeSimulator:
    """Generate and publish simulated cold-chain sensor readings."""

    def __init__(
        self,
        broker_host: str,
        broker_port: int,
        truck_id: str,
        anomaly: str,
        duration_seconds: float,
        seed: int,
        qos: int,
        door_event_probability: float,
    ) -> None:
        self.broker_host = broker_host
        self.broker_port = broker_port
        self.truck_id = truck_id
        self.anomaly = anomaly
        self.duration_seconds = duration_seconds
        self.seed = seed
        self.qos = qos
        self.door_event_probability = door_event_probability

        self.random_generator = np.random.default_rng(seed)
        random.seed(seed)

        self.running = True
        self.connected = False
        self.start_monotonic = 0.0
        self.sequence_number = 0

        self.state = SensorState(
            temperature_c=NORMAL_TEMPERATURE_MEAN_C,
            vibration_rms_g=NORMAL_VIBRATION_MEAN_G,
            door_state="CLOSE",
        )

        self.topic_root = f"logibridge/trucks/{truck_id}"

        self.client = mqtt.Client(
            callback_api_version=mqtt.CallbackAPIVersion.VERSION2,
            client_id=f"logibridge-simulator-{truck_id}",
            protocol=mqtt.MQTTv311,
        )

        self.client.on_connect = self._on_connect
        self.client.on_disconnect = self._on_disconnect
        self.client.on_publish = self._on_publish

    @property
    def temperature_topic(self) -> str:
        return f"{self.topic_root}/sensors/temperature"

    @property
    def vibration_topic(self) -> str:
        return f"{self.topic_root}/sensors/vibration"

    @property
    def door_topic(self) -> str:
        return f"{self.topic_root}/sensors/door"

    @property
    def combined_topic(self) -> str:
        return f"{self.topic_root}/sensors/combined"

    @property
    def status_topic(self) -> str:
        return f"{self.topic_root}/status"

    def _on_connect(
        self,
        client: mqtt.Client,
        userdata: Any,
        flags: mqtt.ConnectFlags,
        reason_code: mqtt.ReasonCode,
        properties: mqtt.Properties | None,
    ) -> None:
        """Handle connection establishment."""

        if reason_code == 0:
            self.connected = True
            LOGGER.info(
                "Connected to MQTT broker at %s:%d",
                self.broker_host,
                self.broker_port,
            )
        else:
            LOGGER.error(
                "MQTT connection failed with reason code: %s",
                reason_code,
            )

    def _on_disconnect(
        self,
        client: mqtt.Client,
        userdata: Any,
        disconnect_flags: mqtt.DisconnectFlags,
        reason_code: mqtt.ReasonCode,
        properties: mqtt.Properties | None,
    ) -> None:
        """Handle broker disconnection."""

        self.connected = False

        if self.running:
            LOGGER.warning(
                "MQTT connection lost. Reason code: %s",
                reason_code,
            )
        else:
            LOGGER.info("Disconnected from MQTT broker")

    def _on_publish(
        self,
        client: mqtt.Client,
        userdata: Any,
        mid: int,
        reason_code: mqtt.ReasonCode,
        properties: mqtt.Properties | None,
    ) -> None:
        """Handle MQTT publish acknowledgement."""

        LOGGER.debug("MQTT message acknowledged: mid=%d", mid)

    def _timestamp(self) -> str:
        """Return a timezone-aware UTC timestamp."""

        return datetime.now(timezone.utc).isoformat(
            timespec="milliseconds"
        ).replace("+00:00", "Z")

    def _elapsed_seconds(self) -> float:
        return time.monotonic() - self.start_monotonic

    def _base_payload(self, sensor: str) -> dict[str, Any]:
        """Create fields shared by every sensor payload."""

        self.sequence_number += 1

        return {
            "schema_version": "1.0",
            "truck_id": self.truck_id,
            "sensor": sensor,
            "timestamp": self._timestamp(),
            "sequence": self.sequence_number,
            "anomaly_mode": self.anomaly,
            "elapsed_seconds": round(self._elapsed_seconds(), 3),
        }

    def _temperature_drift_offset(self, elapsed_seconds):
        """Return a linear temperature-drift """

        reading_index = int(np.floor(elapsed_seconds))
        
        return(reading_index * 0.08)

    def generate_temperature(self) -> float:
        """Generate one temperature reading in degrees Celsius."""

        value = self.random_generator.normal(
            NORMAL_TEMPERATURE_MEAN_C,
            NORMAL_TEMPERATURE_STD_C,
        )

        if self.anomaly in {"temp_drift", "combined"}:
            value += self._temperature_drift_offset(
                self._elapsed_seconds()
            )

        return round(float(value), 3)

    def generate_vibration(self) -> float:
        """Generate one vibration RMS reading in g."""

        if self.anomaly in {"vibration", "combined"}:
            mean_g = 1.2
            standard_deviation_g = 0.15

            value = self.random_generator.normal(
                mean_g,
                standard_deviation_g,
            )

        return round(max(0.0, float(value)), 3)

    def maybe_generate_door_event(self) -> str | None:
        """Optionally toggle and return the cargo-door state."""

        event_probability = self.door_event_probability

        if self.anomaly == "combined":
            event_probability = min(
                event_probability * 3.0,
                0.50,
            )

        if self.random_generator.random() >= event_probability:
            return None

        self.state.door_state = (
            "OPEN"
            if self.state.door_state == "CLOSE"
            else "CLOSE"
        )

        return self.state.door_state

    def publish_json(
        self,
        topic: str,
        payload: dict[str, Any],
        retain: bool = False,
    ) -> None:
        """Publish a dictionary as compact JSON."""

        encoded_payload = json.dumps(
            payload,
            separators=(",", ":"),
            ensure_ascii=False,
        )

        result = self.client.publish(
            topic,
            payload=encoded_payload,
            qos=self.qos,
            retain=retain,
        )

        if result.rc != mqtt.MQTT_ERR_SUCCESS:
            LOGGER.error(
                "Publish failed: topic=%s rc=%s",
                topic,
                result.rc,
            )

    def publish_temperature(self) -> None:
        """Generate and publish one temperature reading."""

        self.state.temperature_c = self.generate_temperature()

        payload = self._base_payload("temperature")
        payload.update(
            {
                "value": self.state.temperature_c,
                "unit": "degC",
                "sample_rate_hz": 1.0,
            }
        )

        self.publish_json(self.temperature_topic, payload)

        LOGGER.info(
            "TEMP  | %7.3f degC | mode=%s",
            self.state.temperature_c,
            self.anomaly,
        )

    def publish_vibration(self) -> None:
        """Generate and publish one vibration reading."""

        self.state.vibration_rms_g = self.generate_vibration()

        payload = self._base_payload("vibration")
        payload.update(
            {
                "value": self.state.vibration_rms_g,
                "unit": "g",
                "sample_rate_hz": 0.5,
            }
        )

        self.publish_json(self.vibration_topic, payload)

        LOGGER.info(
            "VIB   | %7.3f g    | mode=%s",
            self.state.vibration_rms_g,
            self.anomaly,
        )

    def publish_door_event(self, event: str) -> None:
        """Publish a discrete cargo-door event."""

        payload = self._base_payload("door")
        payload.update(
            {
                "event": event,
                "state": self.state.door_state,
            }
        )

        self.publish_json(
            self.door_topic,
            payload,
            retain=True,
        )

        LOGGER.info(
            "DOOR  | %-5s      | mode=%s",
            event,
            self.anomaly,
        )

    def publish_combined_state(self) -> None:
        """Publish the latest fused raw sensor state."""

        payload = self._base_payload("combined")
        payload.update(asdict(self.state))

        self.publish_json(self.combined_topic, payload)

    def publish_status(self, status: str) -> None:
        """Publish retained simulator status."""

        payload = {
            "schema_version": "1.0",
            "truck_id": self.truck_id,
            "timestamp": self._timestamp(),
            "status": status,
            "anomaly_mode": self.anomaly,
        }

        self.publish_json(
            self.status_topic,
            payload,
            retain=True,
        )

    def connect(self) -> None:
        """Connect to the MQTT broker and start its network loop."""

        LOGGER.info(
            "Connecting to MQTT broker %s:%d",
            self.broker_host,
            self.broker_port,
        )

        self.client.connect(
            self.broker_host,
            self.broker_port,
            keepalive=60,
        )

        self.client.loop_start()

        connection_deadline = time.monotonic() + 10.0

        while not self.connected:
            if time.monotonic() >= connection_deadline:
                raise TimeoutError(
                    "Timed out while connecting to the MQTT broker"
                )

            time.sleep(0.05)

    def stop(self) -> None:
        """Request a graceful simulator shutdown."""

        self.running = False

    def run(self) -> None:
        """Run the real-time sensor simulation loop."""

        self.connect()
        self.start_monotonic = time.monotonic()

        self.publish_status("ONLINE")
        self.publish_door_event(self.state.door_state)

        next_temperature_time = self.start_monotonic
        next_vibration_time = self.start_monotonic
        next_combined_time = self.start_monotonic

        LOGGER.info(
            "Simulation started: truck=%s anomaly=%s duration=%s",
            self.truck_id,
            self.anomaly,
            (
                "unlimited"
                if self.duration_seconds == 0
                else f"{self.duration_seconds:.1f}s"
            ),
        )

        LOGGER.info("Temperature topic: %s", self.temperature_topic)
        LOGGER.info("Vibration topic: %s", self.vibration_topic)
        LOGGER.info("Door topic: %s", self.door_topic)
        LOGGER.info("Combined topic: %s", self.combined_topic)

        try:
            while self.running:
                now = time.monotonic()
                elapsed = now - self.start_monotonic

                if (
                    self.duration_seconds > 0
                    and elapsed >= self.duration_seconds
                ):
                    LOGGER.info(
                        "Requested simulation duration completed"
                    )
                    break

                if now >= next_temperature_time:
                    self.publish_temperature()
                    next_temperature_time += (
                        TEMPERATURE_SAMPLE_INTERVAL_SECONDS
                    )

                    event = self.maybe_generate_door_event()

                    if event is not None:
                        self.publish_door_event(event)

                if now >= next_vibration_time:
                    self.publish_vibration()
                    next_vibration_time += (
                        VIBRATION_SAMPLE_INTERVAL_SECONDS
                    )

                if now >= next_combined_time:
                    self.publish_combined_state()
                    next_combined_time += (
                        TEMPERATURE_SAMPLE_INTERVAL_SECONDS
                    )

                next_event_time = min(
                    next_temperature_time,
                    next_vibration_time,
                    next_combined_time,
                )

                sleep_seconds = max(
                    0.01,
                    min(0.10, next_event_time - time.monotonic()),
                )

                time.sleep(sleep_seconds)

        finally:
            self.shutdown()

    def shutdown(self) -> None:
        """Publish offline status and close the MQTT connection."""

        if self.connected:
            self.publish_status("OFFLINE")
            time.sleep(0.15)

        self.running = False
        self.client.loop_stop()
        self.client.disconnect()

        LOGGER.info("Simulation stopped")


def generate_offline_samples(
    anomaly,
    duration_seconds,
    seed=42,
):
    """Generate synchronized samples using C1 anomaly definitions."""

    if anomaly not in {
        "none",
        "temp_drift",
        "vibration",
        "combined",
    }:
        raise ValueError(
            "Unsupported anomaly mode: "
            + str(anomaly)
        )

    generator = np.random.default_rng(seed)

    samples = []
    latest_vibration = NORMAL_VIBRATION_MEAN_G
    door_state = "CLOSE"

    for second in range(
        int(duration_seconds) + 1
    ):
        temperature = generator.normal(
            NORMAL_TEMPERATURE_MEAN_C,
            NORMAL_TEMPERATURE_STD_C,
        )

        if anomaly in {
            "temp_drift",
            "combined",
        }:
            temperature += (
                second * 0.08
            )

        if second % 2 == 0:
            if anomaly in {
                "vibration",
                "combined",
            }:
                latest_vibration = (
                    generator.normal(
                        1.2,
                        0.15,
                    )
                )
            else:
                latest_vibration = (
                    generator.normal(
                        NORMAL_VIBRATION_MEAN_G,
                        NORMAL_VIBRATION_STD_G,
                    )
                )

        latest_vibration = max(
            0.0,
            float(latest_vibration),
        )

        if generator.random() < 0.004:
            door_state = (
                "OPEN"
                if door_state == "CLOSE"
                else "CLOSE"
            )

        samples.append(
            {
                "timestamp": float(second),
                "temperature_c": float(
                    temperature
                ),
                "vibration_rms_g": (
                    latest_vibration
                ),
                "vibration_updated": (
                    second % 2 == 0
                ),
                "door_state": door_state,
            }
        )

    return samples
    

def probability(value: str) -> float:
    """Validate a command-line probability value."""

    parsed_value = float(value)

    if not 0.0 <= parsed_value <= 1.0:
        raise argparse.ArgumentTypeError(
            "probability must be between 0 and 1"
        )

    return parsed_value


def non_negative_float(value: str) -> float:
    """Validate a non-negative floating-point argument."""

    parsed_value = float(value)

    if parsed_value < 0:
        raise argparse.ArgumentTypeError(
            "value must be zero or greater"
        )

    return parsed_value


def build_argument_parser() -> argparse.ArgumentParser:
    """Build the simulator command-line interface."""

    parser = argparse.ArgumentParser(
        description=(
            "Publish simulated cold-chain sensor readings over MQTT."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--broker",
        default="127.0.0.1",
        help="MQTT broker hostname or IP address",
    )

    parser.add_argument(
        "--port",
        type=int,
        default=1883,
        help="MQTT broker TCP port",
    )

    parser.add_argument(
        "--truck-id",
        default="TRUCK-001",
        help="Truck identifier used in the MQTT topic hierarchy",
    )

    parser.add_argument(
        "--anomaly",
        choices=[
            "none",
            "temp_drift",
            "vibration",
            "combined",
        ],
        default="none",
        help="Anomaly scenario to simulate",
    )

    parser.add_argument(
        "--duration",
        type=non_negative_float,
        default=60.0,
        help=(
            "Simulation duration in seconds; use 0 to run until "
            "Ctrl+C"
        ),
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible sensor readings",
    )

    parser.add_argument(
        "--qos",
        choices=[0, 1, 2],
        type=int,
        default=DEFAULT_QOS,
        help="MQTT Quality of Service level",
    )

    parser.add_argument(
        "--door-event-probability",
        type=probability,
        default=DEFAULT_DOOR_EVENT_PROBABILITY,
        help="Probability of toggling the door at each 1 Hz cycle",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable detailed debug logging",
    )

    return parser


def configure_logging(verbose: bool) -> None:
    """Configure console logging."""

    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format=(
            "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
        ),
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def main() -> int:
    """CLI entry point."""

    parser = build_argument_parser()
    arguments = parser.parse_args()

    configure_logging(arguments.verbose)

    simulator = LogiBridgeSimulator(
        broker_host=arguments.broker,
        broker_port=arguments.port,
        truck_id=arguments.truck_id,
        anomaly=arguments.anomaly,
        duration_seconds=arguments.duration,
        seed=arguments.seed,
        qos=arguments.qos,
        door_event_probability=arguments.door_event_probability,
    )

    def handle_shutdown_signal(
        signal_number: int,
        frame: Any,
    ) -> None:
        del frame

        LOGGER.info(
            "Received signal %d; requesting graceful shutdown",
            signal_number,
        )

        simulator.stop()

    signal.signal(signal.SIGINT, handle_shutdown_signal)
    signal.signal(signal.SIGTERM, handle_shutdown_signal)

    try:
        simulator.run()
    except ConnectionRefusedError:
        LOGGER.error(
            "Connection refused by MQTT broker at %s:%d. "
            "Verify that Mosquitto is running.",
            arguments.broker,
            arguments.port,
        )
        return 1
    except KeyboardInterrupt:
        simulator.stop()
        return 0
    except Exception:
        LOGGER.exception("Simulator terminated unexpectedly")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
